language: node_js
node_js:
  - "8"

before_install:
  - "[ -d test/Step\\ BYOND] || curl -o StepBYOND.zip http://files.byondhome.com/download/Deadron/StepBYOND"
  - "[ -d test/Step\\ BYOND] || unzip StepBYOND.zip -d test"
  - "[ -d test/Your\\ First\\ World ] || curl -o YourFirstWorld.zip http://files.byondhome.com/download/Dantom/YourFirstWorld"
  - "[ -d test/Your\\ First\\ World ] || unzip YourFirstWorld.zip -d test"

cache:
  directories:
    - "test/Step BYOND"
    - "test/Your First World"
