language: node_js
node_js:
  - "8"

before_install:
  - "[ -d Step\\ BYOND] || curl -o StepBYOND.zip http://files.byondhome.com/download/Deadron/StepBYOND"
  - "[ -d Step\\ BYOND] || unzip StepBYOND.zip"
  - "[ -d Your\\ First\\ World ] || curl -o YourFirstWorld.zip http://files.byondhome.com/download/Dantom/YourFirstWorld"
  - "[ -d Your\\ First\\ World ] || unzip YourFirstWorld.zip"

cache:
  directories:
    - "Step BYOND"
    - "Your First World"
